<a href="https://colab.research.google.com/github/developer525/collab-repository/blob/main/devanjal_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PYTHON ,NUMPY AND VECTORISATION

In [47]:
import numpy as np
import time

In maths index are from 01 to n.
In computer science index runs from 0 to n-1

In [48]:
#Numpy routines which allocate memory and fill arrays with value
a = np.zeros(4);
print(f"np.zeros(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a= np.zeros((4,));
print(f"np.zeros(4,) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a= np.random.random_sample(4);
print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4) :   a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeros(4,) :  a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.random.random_sample(4): a = [0.44236513 0.04997798 0.77390955 0.93782363], a shape = (4,), a data type = float64


In [49]:
#Numpy routines which allocate memory and fill arrays with values but do not accept shape as input
a = np.arange(4.);
print(f"np.arange(4.):     a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.rand(4);
print(f"np.random.rand(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.arange(4.):     a = [0. 1. 2. 3.], a shape = (4,), a data type = float64
np.random.rand(4): a = [0.5792328  0.53516563 0.80204309 0.24814448], a shape = (4,), a data type = float64


In [50]:
#Numpy routines which allocate memory and fill with user specified values
a = np.array([5,4,3,2]);
print(f"np.array([5,4,3,2]):  a = {a},     a shape = {a.shape}, a data type = {a.dtype}")
a = np.array([5.,4,3,2]);
print(f"np.array([5.,4,3,2]): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.array([5,4,3,2]):  a = [5 4 3 2],     a shape = (4,), a data type = int64
np.array([5.,4,3,2]): a = [5. 4. 3. 2.], a shape = (4,), a data type = float64


**INDEXING**

In [51]:
a = np.arange(10)
print(a)

#access an element
print(a[2])

#access the last element, negative indexes count from the end
print(a[-1])

#indexs must be within the range of the vector or they will produce and error
try:
    c = a[10]
except Exception as e:
    print("The error message you'll see is:")
    print(e)


[0 1 2 3 4 5 6 7 8 9]
2
9
The error message you'll see is:
index 10 is out of bounds for axis 0 with size 10


**SLICING**

In [52]:
a =np.arange(10)
print(f"a         = {a}")

#access 5 consecutive elements (start:stop:step)
c = a[2:7:1];
print("a[2:7:1] = ", c)  #slicing leaves the last stop

#access 3 elements separated by 2
c = a[2:7:2];
print("a[2:7:2] = ", c)

#access all elements with index 3 and above
c = a[3::]
print("a[3::] = ", c)

#access all elements with index less than 3
c = a[:3]
print("a[:3] = ",c)

#access all elements
c = a[:]
print("a[:] ", c)

a         = [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] =  [2 3 4 5 6]
a[2:7:2] =  [2 4 6]
a[3::] =  [3 4 5 6 7 8 9]
a[:3] =  [0 1 2]
a[:]  [0 1 2 3 4 5 6 7 8 9]


SINGLE VECTOR OPERATIONS

In [53]:
a = np.array([1,2,3,4])
print(f"a             : {a}")

#negate elements of a
b = -a
print(f"b = -a        : {b}")

#sum all elements of a, returns a scalar
b = np.sum(a)
print(f"b = np.sum(a) : {b}")

b = np.mean(a)
print(f"b = np.mean(a) : {b}")

b = a**2
print(f"b = a**2      : {b}")

a             : [1 2 3 4]
b = -a        : [-1 -2 -3 -4]
b = np.sum(a) : 10
b = np.mean(a) : 2.5
b = a**2      : [ 1  4  9 16]


**VECTOR VECTOR ELEMENT WISE OPERATIONS**

In [54]:
a = np.array([ 1, 2, 3, 4])
b = np.array([-1,-2, 3, 4])
print(f"Binary operators work element wise: {a + b}")
print(a.dtype)
print(b.dtype)
print(a.shape)
print(b.shape)

Binary operators work element wise: [0 0 6 8]
int64
int64
(4,)
(4,)


In [55]:
#try a mismatch vector operations
c = np.array([1,2])
try:
    d = a + c
except Exception as e:
    print("The error message you'll see is:")
    print(e)

The error message you'll see is:
operands could not be broadcast together with shapes (4,) (2,) 


**SCALAR VECTOR OPERATIONS**

In [56]:
a = np.array([1,2,3,4])

#multiply a by a scalar
b = 5 * a
print(f"b = 5 * a : {b}")

b = 5 * a : [ 5 10 15 20]


**VECTOR VECTOR DOT PRODUCT**

In [57]:
def my_dot(a,b):
  """
  Compute the dot product of two vectors

  Args:
    a (ndarray (n,)):  input vector
    b (ndarray (n,)):  input vector with same dimension as a

    Returns:
    x (scalar):
  """
  x = 0
  for i in range(a.shape[0]):
    x = x + a[i] * b[i]
  return x


In [58]:
# test 1-D
a = np.array([1,2,3,4])
b = np.array([-1,4,3,2])
print(f"my_dot(a,b) = {my_dot(a,b)}")
c = np.dot(b,a)
print(c)


my_dot(a,b) = 24
24


**THE NEED FOR SPEED**

In [59]:
np.random.seed(1)
a = np.random.rand(10000000)
b = np.random.rand(10000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(f"np.dot(a,b) = {c:.4f}")
print(f"Vectorized version duration: {1000*(toc-tic):.4f} ms")

np.dot(a,b) = 2501072.5817
Vectorized version duration: 17.7283 ms


In [60]:
tic = time.time()
c = my_dot(a,b)
toc = time.time()

print(f"my_dot(a,b) = {c:.4f}")
print(f"loop version duration: {1000*(toc-tic):.4f} ms")

my_dot(a,b) = 2501072.5817
loop version duration: 3867.4507 ms


In [61]:
#del(a); delete a uncomment
#del(b); delete b uncomment
a
b

array([0.49884527, 0.5194437 , 0.9480511 , ..., 0.99416697, 0.61599986,
       0.41453835])

**VECTOR VECTOR OPERATIONS**

In [62]:
#show common course example
X = np.array([[1],[2],[3],[4]])
w = np.array([2])
c = np.dot(X[1],w)
print(c)

4


In [63]:
print(f"X[1] has shape {X[1].shape}")
print(f"w has shape {w.shape}")
print(f"c has shape {c.shape}")

X[1] has shape (1,)
w has shape (1,)
c has shape ()


MATRIX CREATION

In [64]:
a = np.zeros((1,5))
print(f"a shape= {a.shape}, a= {a}")

a[0,1] = 5
print(f"a shape= {a.shape}, a= {a}")

a[0,2] = 10
print(f"a shape= {a.shape}, a= {a}")

a shape= (1, 5), a= [[0. 0. 0. 0. 0.]]
a shape= (1, 5), a= [[0. 5. 0. 0. 0.]]
a shape= (1, 5), a= [[ 0.  5. 10.  0.  0.]]


Numpy routines which allocate memory and fill user specified values

In [65]:
a = np.array([[5] , [4] , [3]]);
print(f"a shape= {a.shape}, a= {a}")

a shape= (3, 1), a= [[5]
 [4]
 [3]]


In [66]:
a = np.array([[5], [4], [3]]);
print(f"a shape= {a.shape}, a= {a}")

a shape= (3, 1), a= [[5]
 [4]
 [3]]


**Operations on Matrices**

**Indexing**

In [67]:
a =  np.arange(6).reshape(-1,2)
print(f"a.shape: {a.shape}, \na= {a}")

a.shape: (3, 2), 
a= [[0 1]
 [2 3]
 [4 5]]


In [68]:
#access an element
print(f"\na[2,0].shape = {a[2,0].shape}")
print(f"a[2,0] = {a[2,0]}")
print(f"\na[2].shape = {a[2].shape}")
print(f"a[2] = {a[2]}")
print(f"\nThe last element is {a[-1,-1]}")


a[2,0].shape = ()
a[2,0] = 4

a[2].shape = (2,)
a[2] = [4 5]

The last element is 5


**SLICING**

In [69]:
#Vector 2-D slicing operations
a = np.arange(20).reshape(-1,10)
print(f"a = \n{a}")

#access 5 consecutive elements (start:stop:step)
print("a[0,2:7:1] = ", a[0,2:7:1])

a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0,2:7:1] =  [2 3 4 5 6]


In [70]:
#access 5 consecutive elements (start:stop:step) in 2 rows
print("a[:,2:7:1] = \n", a[:,2:7:1])

a[:,2:7:1] = 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]]


In [71]:
#access all elements
print("a[:,:] = \n", a[:,:])

a[:,:] = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [72]:
#access all elemens in one row(very common usage)
print("a[1,:] = ", a[1,:])


a[1,:] =  [10 11 12 13 14 15 16 17 18 19]


In [73]:
#same as
print("a[1] = ", a[1])

a[1] =  [10 11 12 13 14 15 16 17 18 19]
